CREATE TABLE `blockchain`.`stm_divide` (
  `id` BIGINT(20) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `pledged` BIGINT(20) NOT NULL,
  `total_pledged` BIGINT(20) NOT NULL,
  `total_bonus` BIGINT(20) NOT NULL,
  `reward` BIGINT(20) NOT NULL,
  `trx_hash` VARCHAR(200) NULL,
  `trx_result` VARCHAR(45) NULL,
  `c_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `m_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`));

CREATE TABLE `blockchain`.`stm_pool` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `caller_address` VARCHAR(100) NOT NULL,
  `pool_address` VARCHAR(100) NOT NULL,
  `total_amount` BINARY(20) NOT NULL DEFAULT 0,
  `trx_hash` VARCHAR(500) NULL,
  `trx_result` VARCHAR(45) NOT NULL DEFAULT 1,
  `c_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `m_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (`id`));
